const ACTIONS = {
  LOAD_CARDS: 'LOAD_CARDS',
  CREATE_CARD: 'CREATE_CARD',
  SET_CARD_FOR_SALE_CARD: 'SET_CARD_FOR_SALE_CARD',
  UPDATE_CARD: "UPDATE_CARD",
  DELETE_CARD: 'DELETE_CARD',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
};

export default ACTIONS;