const ACTIONS = {
  LOAD_CARDS: 'LOAD_CARDS',
  CREATE_CARD: 'CREATE_CARD',
  SET_CARD_FOR_SALE: 'SET_CARD_FOR_SALE',
  UPDATE_CARD: "UPDATE_CARD",
  DELETE_CARD: 'DELETE_CARD',
  BUY_CARD: 'BUY_CARD',
  UPDATE_BALANCE: 'UPDATE_BALANCE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
};

export default ACTIONS;